.\" 
.TH "FOSMOUNT" "1" "July 2009" "fosmount" "User Commands"
.SH "NAME"
fosmount \- FOS mounter for fuse
.SH "SYNOPSIS"
.B fosmount
[\fIoptions\fR] \fIdevice mountpoint\fR
.SH "DESCRIPTION"
FUSE extension for a read\-only access on Smaky FOS.
.TP 
\fB\-h\fR \fB\-\-help\fR
Display help message.
.TP 
\fB\-v\fR \fB\-\-version\fR
Show version.
.TP 
\fB\-a\fR \fB\-\-harddisk\fR
Force an hard disk instead of the autodetection.
.TP 
\fB\-f\fR \fB\-\-floppydisk\fR
Force a floppy disk instead of the autodetection.
.TP 
\fB\-l\fR \fB\-\-fos\-logger\fR
Turn ON the FOS logger, fosmount will not be detached of the terminal.
.TP 
\fB\-d\fR \fB\-\-fuse\-debugger\fR
Turn ON the FUSE debugger, fosmount will not be detached of the terminal.
.TP 
\fB\-i\fR \fB\-\-image\-pbm\fR
Convert on the fly .IMAGE to .PBM (portable bitmap format).
.TP 
\fB\-j\fR \fB\-\-image\-xpm\fR
Convert on the fly .COLOR to .XPM (X Pixmap version 2).
.TP 
\fBdevice\fR
/dev/fd0 for floppy disk
.br 
/dev/sda for hard disk, etc, ...
.TP 
\fBmountpoint\fR
Mount point for the FOS, like /mnt/smaky.
.SH "AUTHOR"
Written by Mathieu Schroeter <mathieu.schroeter@gamesover.ch>.
.SH "REPORTING BUGS"
Report bugs to <\fIfosfat\-devel@gamesover.ch\fP>.
.SH "COPYRIGHT"
Copyright \(co 2006\-2010 Mathieu Schroeter

This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH "SEE ALSO"
fosread(1)
