.\" 
.TH "FOSREAD" "1" "July 2009" "fosread" "User Commands"
.SH "NAME"
fosread \- FOS reader
.SH "SYNOPSIS"
.B fosread
[\fIoptions\fR] \fIdevice mode \fR[\fInode\fR] [\fIpath\fR]
.SH "DESCRIPTION"
Tool for a read\-only access on Smaky FOS.
.TP 
\fB\-h\fR \fB\-\-help\fR
Display help message.
.TP 
\fB\-v\fR \fB\-\-version\fR
Show version.
.TP 
\fB\-a\fR \fB\-\-harddisk\fR
Force an hard disk instead of the autodetection.
.TP 
\fB\-f\fR \fB\-\-floppydisk\fR
Force a floppy disk instead of the autodetection.
.TP 
\fB\-l\fR \fB\-\-fos\-logger\fR
Turn ON the FOS logger.
.TP 
\fB\-u\fR \fB\-\-undelete\fR
enable the undelete mode, even deleted files will be listed and sometimes restorable with \fBget\fR mode.
.TP 
\fBdevice\fR
/dev/fd0 for floppy disk
.br 
/dev/sda for hard disk, etc, ...
.TP 
\fBmode\fR
\fBlist\fR : list the content of a node
.br 
\fBget\fR  : copy a file from the Smaky disk in a local directory
.TP 
\fBnode\fR
The tree with the file (or folder) for \fBget\fR or \fBlist\fR.
.br 
example: foo/bar/toto.text
.TP 
\fBpath\fR
You can specify a path to save the file (with \fBget\fR mode).
.SH "AUTHOR"
Written by Mathieu Schroeter <mathieu@schroetersa.ch>.
.SH "REPORTING BUGS"
Report bugs to <\fImathieu@schroetersa.ch\fP>.
.SH "COPYRIGHT"
Copyright \(co 2006\-2009 Mathieu Schroeter

This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
