.TH SMASCII "1" "March 2010" "help2man and hand edition" "User Commands"
.SH NAME
smascii \- smascii
.SH SYNOPSIS
.B smascii
\fIsmaky_file converted_file \fR[\fI--unix\fR]
.SH DESCRIPTION
Tool to convert Smaky text file to Extended ASCII (ISO\-8859\-1).
.TP
smaky_file
the smaky text file
.TP
converted_file
the file converted
.TP
\fB\-\-unix\fR
the Carriage Return (Old Mac) will be
converted to Line Feed (unix)
.SH BUGS
.PP
Please, report bugs to <mathieu@schroetersa.ch>.
.SH AUTHOR
.PP
This manpage was written for Debian, starting with a help2man output, by
Didier Raboud <didier@raboud.com>, on the 4. March 2010.
